neutrino:
  application:
    name: neutrino-proxy-client

  proxy:
    protocol:
      max-frame-length: 2097152
      length-field-offset: 0
      length-field-length: 4
      initial-bytes-to-strip: 0
      length-adjustment: 0
      read-idle-time: 40
      write-idle-time: 5
      all-idle-time-seconds: 0
    client:
      thread-count: 50
      key-store-password: ${STORE_PASS:123456}
      jks-path: ${JKS_PATH:classpath:/test.jks}
      server-ip: ${SERVER_IP:localhost}
      server-port: ${SERVER_PORT:9002}
      ssl-enable: ${SSL_ENABLE:true}
      obtain-license-interval: 5
      license-key: ${LICENSE_KEY:b0a907332b474b25897c4dcb31fc7eb6}
